# Generated by Django 3.2.25 on 2025-03-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0006_auto_20250311_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='DissertationDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('student_signature', models.CharField(max_length=100)),
                ('supervisor_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.supervisor')),
            ],
        ),
    ]
