# Generated by Django 3.2.25 on 2025-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20250301_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='available_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
